### ISSUE TITLE
Gull data paper

### ISSUE THREAD

**Issue by peterdesmet** [LifeWatchINBO/data-publication#46]
## Before submitting

* [x] Update title
* [x] Add figures
* [x] Update dataset metadata: everything except study extent
* [x] Update dataset data
* [x] Republish dataset
* [x] Submit

## After review

* [x] Update text

## After acceptance

* [x] Finalize text (with correct version number for dataset)
* [x] Update dataset metadata
* [x] Update dataset title
* [x] Add dataset authors
* [x] Add Vlissingen colony to map
* [x] Update figure 1
* [x] Update dataset data mapping: title
* [x] Update data
* [x] Update [metadata.md](https://github.com/LifeWatchINBO/data-publication/blob/master/datasets/bird-tracking-gull-occurrences/metadata.md)

## After DOI is known

* [x] Add paper DOI to metadata.md (2 places)
* [x] Add paper DOI to IPT (2 places)
* [x] Add paper reference to metadata.md (as first reference)
* [x] Add paper reference to IPT (as first reference)
* [x] Add paper reference to README
* [x] Republish dataset
* [x] Update dataset on VODP (also citation)

**Comment by peterdesmet** [comment]
DOI is known: http://doi.org/10.3897/zookeys.555.6173 I'll update where I can.
