### ISSUE TITLE
Update visfauna-ijzer-occurrences SQL

### ISSUE THREAD

**Issue by peterdesmet** [LifeWatchINBO/data-publication#71]
_Note: Data verified for version 9.3 on 2015-10-01. **Metadata** has been completely verified and updated, to comply with our new guidelines regarding usage norms, recourse citation, etc (except for project info)._

Changes to apply for occurrence core:

* [ ] Use lowerCamelCase field names
* [x] Map `occurrenceID` instead of `GUID`
* [ ] Remove `modified`
* [ ] Update `language` to `en`
* [x] Rename `license` to `rights`
* [x] Update `accessRights`
* [ ] Use dataset DOI in `datasetID`
* [x] Remove `collectionCode`
* [ ] Update `datasetName` (pending #70)
* [x] Use `HumanObservation` for `basisOfRecord`
* [x] Remove `catalogNumber`
* [x] Verify `individualCount`: all reasonable numbers (1-275), but 31 records have `0`
* [x] Lowercase `samplingProtocol`
* [ ] Remove `verbatimDate`: it is exactly the same as `eventDate`
* [ ] Verify `verbatimLongitude`, are the numbers not missing a digit: `39235`?
* [ ] Update `verbatimCoordinateSystem` to `Belgian Lambert 72`
* [ ] Update `verbatimSRS` to `Belgian Datum 1972`
* [ ] Add `georeferenceProtocol`
* [ ] Add `georeferenceSources`
* [ ] Add `georeferenceVerificationStatus`
* [ ] Remove `dateIdentified`
* [ ] Add `Actinopterygii` as `class`
* [x] Verify `taxonRank`: are those all species? Yes, all species.
* [ ] Add `vernacularName`
* [ ] Remove unmapped columns
* [ ] Apply changes in production

Changes to apply for measurement extension:

* [ ] Update `measurementType` to use lowercase: `length` #32
* [ ] Remove `modified`

Questions:

* [ ] What do we do with `individualCount` = 0 (31 records)?
* [ ] This is a dataset about juvenile fish. Shouldn't we add `lifeStage`? See also #70 
* [ ] Should we use `electro fishing` or `electrofishing` in `samplingProtocol`? What is used in VIS?
* [ ] Can we add a `samplingEffort`?
* [ ] Shouldn't we split `verbatimLocality` in `verbatimLocality` and `habitat`. E.g. `Paaiplaats Sint Jorisput` or `Natuurlijk Elzendamme SO`.
